server:
  port: 8080

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/bank_db?sslmode=disable
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: bank_schema

  liquibase:
    changelog: classpath:db/migration/db.changelog-master.yml
    enabled: true
    default-schema: bank_schema

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secretKey: c29tZVNlY3JldA==
    tokenExpiration: 20d

springdoc:
  swagger-ui:
    path: /swagger-ui


#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
