server:
  port: 8080

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/bank_db?sslmode=disable
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: bank_schema

  liquibase:
    changelog: classpath:db/migration/db.changelog-master.yml
    enabled: true
    default-schema: bank_schema

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secretKey: ${JWT_SECRET:VGhlIGZhc3Rlc3QgYW5kIG1vc3Qgc2VjdXJlIEJhc2U2NCBlbmNvZGluZyBhbmQgZGVjb2RpbmcgdG9vbA==}
    tokenExpiration: 30m
  cardNumberHasher:
    secretKey: ${CARD_HASH_SECRET:VGhpcyBlbmNvZGluZyBoZWxwcyB0byBlbnN1cmUgdGhhdCB0aGUgZGF0YSByZW1haW5zIGludGFjdCB3aXRob3V0IG1vZGlmaWNhdGlvbiBkdXJpbmcgdHJhbnNwb3J0Lg==}

springdoc:
  swagger-ui:
    path: /swagger-ui

bootstrap:
  admin:
    password: ${ADMIN_PASSWORD:admin}


#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
